# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('plurals_zero', models.CharField(blank=True, max_length=128)),
                ('plurals_one', models.CharField(blank=True, max_length=128)),
                ('plurals_two', models.CharField(blank=True, max_length=128)),
                ('plurals_few', models.CharField(blank=True, max_length=128)),
                ('plurals_many', models.CharField(blank=True, max_length=128)),
                ('plurals_other', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('strings_upload_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value_one', models.TextField(blank=True)),
                ('value_other', models.TextField()),
                ('markers', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('last_access_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='core.Project')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('plural_form', models.CharField(choices=[('zero', 'Zero'), ('one', 'One'), ('two', 'Two'), ('few', 'Few'), ('many', 'Many'), ('other', 'Other')], default='other', max_length=8)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.NullBooleanField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.String')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Project')),
            ],
            options={
                'ordering': ('language__name',),
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('alias', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Suggestion')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Translator')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.Translation'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.Translator'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('translator', 'suggestion')]),
        ),
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together=set([('translation', 'string', 'value', 'plural_form')]),
        ),
        migrations.AlterUniqueTogether(
            name='string',
            unique_together=set([('project', 'name')]),
        ),
    ]
