# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.TextField()),
                ('plurals_zero', models.TextField(blank=True)),
                ('plurals_one', models.TextField(blank=True)),
                ('plurals_two', models.TextField(blank=True)),
                ('plurals_few', models.TextField(blank=True)),
                ('plurals_many', models.TextField(blank=True)),
                ('plurals_other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.TextField()),
                ('languages', models.ManyToManyField(related_name='_project_languages_+', to='translate.Language')),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value_one', models.TextField(blank=True)),
                ('value_other', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='translate.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='string',
            unique_together=set([('project', 'name')]),
        ),
    ]
